version: '3'

services:
  server:
    build: ./server
    image: server:latest
    stdin_open: true
    tty: true
    container_name: server
    volumes:
      - "./server:/server"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONHASHSEED=0
      - SERVER_PORT=12345
      - SERVER_LISTEN_BACKLOG=500
      - LOGGING_LEVEL=DEBUG
      - FILE_WORKERS=20
      - ROUTER_P_SIZE=20
      - RESPONSER_P_SIZE=20
    networks:
      - logging_pipeline_net
  client:
    build: ./client
    image: client:latest
    container_name: client
    volumes:
      - "./client:/client"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - CLI_ID=1
      - CLI_SERVER_ADDRESS=server
      - CLI_SERVER_WRITE_PORT=12345
      - TEST=${TEST}
    networks:
      - logging_pipeline_net
    depends_on:
      - server
networks:
  logging_pipeline_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
