version: '3'

services:
  server:
    build:
      dockerfile: src/server/Dockerfile
      context: .
    stdin_open: true
    tty: true
    container_name: server
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONHASHSEED=0
      - SERVER_LISTEN_BACKLOG=1
      - LOGGING_LEVEL=DEBUG
      - FILE_WORKERS=1
      - ROUTER_P_SIZE=20
      - RESPONSER_P_SIZE=20
    networks:
      - logging_pipeline_net
  client:
    build:
      dockerfile: src/client/Dockerfile
      context: .
    container_name: client
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - CLI_ID=1
      - CLI_SERVER_ADDRESS=server
      - CLI_SERVER_WRITE_PORT=12345
      - TEST=${TEST}
    networks:
      - logging_pipeline_net
    depends_on:
      - server
networks:
  logging_pipeline_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
